apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  volumeName: redis-pv
  resources:
    requests:
      storage: 5Gi
