apiVersion: v1
kind: Service
metadata:
  name: harbor-redis
  namespace: harborfinal
spec:
  selector:
    app: harbor-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP