apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-redis
  namespace: harborfinal
  labels:
    app: harbor-redis
spec:
  serviceName: harbor-redis
  replicas: 1
  selector:
    matchLabels:
      app: harbor-redis
  template:
    metadata:
      labels:
        app: harbor-redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: harbor-redis-pvc