apiVersion: v1
kind: Secret
metadata:
  name: harbor-tls
  namespace: harbor
  labels:
    app: harbor
type: kubernetes.io/tls
data:
 tls.crt: <base64_encoded_tls.crt>
 tls.key: <base64_encoded_tls.key>
