namespace: harborfinal

postgresql:
  enabled: true
  image: postgres:15
  replicas: 1
  database: registry
  username: harbor
  passwordSecretName: harbor-db-secret
  storage:
    size: 10Gi
    storageClass: gp3-csi
    accessModes:
      - ReadWriteOnce

exporters:
  postgresql:
    enabled: true
    image: postgresql-exporter:latest
    service:
      port: 9187

serviceMonitor:
  enabled: true
  namespace: harborfinal

persistence:
  volumes:
    - name: harbor-core-pv
      claim: harbor-core-pvc
      size: 5Gi
      accessModes: ReadWriteOnce
      volumeID: vol-0123456789abcdef0

    - name: registry-pv
      claim: registry-pvc
      size: 20Gi
      accessModes: ReadWriteOnce
      volumeID: vol-0abcdef1234567890

    - name: jobservice-pv
      claim: jobservice-pvc
      size: 5Gi
      accessModes: ReadWriteOnce
      volumeID: vol-0a1b2c3d4e5f67890

    - name: portal-pv
      claim: portal-pvc
      size: 5Gi
      accessModes: ReadWriteOnce
      volumeID: vol-0123abcd4567ef890

    - name: trivy-pv
      claim: trivy-pvc
      size: 10Gi
      accessModes: ReadWriteOnce
      volumeID: vol-09abcdef012345678

    - name: postgresql-pv
      claim: postgresql-pvc
      size: 10Gi
      accessModes: ReadWriteOnce
      volumeID: vol-0f1e2d3c4b5a67890

    - name: redis-pv
      claim: redis-pvc
      size: 5Gi
      accessModes: ReadWriteOnce
      volumeID: vol-0a1b2c3d4e5f67891
