namespace: harborfinal

postgresql:
  enabled: true
  image: postgres:15
  replicas: 1
  database: registry
  username: harbor
  passwordSecretName: harbor-db-secret
  storage:
    size: 10Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

harborCore:
  persistence:
    size: 5Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

jobservice:
  persistence:
    size: 5Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

portal:
  persistence:
    size: 5Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

redis:
  persistence:
    size: 5Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

registry:
  persistence:
    size: 20Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

trivy:
  persistence:
    size: 10Gi
    storageClass: ebs-gp3
    accessModes:
      - ReadWriteOnce

exporters:
  postgresql:
    enabled: true
    image: postgresql-exporter:latest
    service:
      port: 9187

serviceMonitor:
  enabled: true
  namespace: harborfinal
