apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-postgresql-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  hostPath:
    path: "/mnt/data/harbor-postgresql"