apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  awsElasticBlockStore:
    volumeID: vol-097daf816c0760af7
    fsType: ext4
