apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: postgresql-pv
  resources:
    requests:
      storage: 10Gi
