apiVersion: v1
kind: Service
metadata:
  name: harbor-postgresql
  namespace: harborfinal
spec:
  selector:
    app: harbor-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer