apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-postgresql
  namespace: harborfinal
  labels:
    app: harbor-postgresql
spec:
  serviceName: harbor-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: harbor-postgresql
  template:
    metadata:
      labels:
        app: harbor-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "registry"
            - name: POSTGRES_USER
              value: "harbor"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-db-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: harbor-postgresql-pvc