apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-trivy-config
  namespace: harborfinal
  labels:
    app: harbor-trivy
data:
  trivy.yaml: |
    server:
      listen: ":8080"
      cacheDir: "/var/lib/trivy"