apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
