apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
