apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
  namespace: harbor
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
