apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: trivy-pv
  resources:
    requests:
      storage: 10Gi
      storageClassName: ebs-gp3

