apiVersion: v1
kind: Service
metadata:
  name: harbor-trivy
  namespace: harborfinal
spec:
  selector:
    app: harbor-trivy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer