apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
  namespace: harborfinal
  labels:
    app: harbor-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-portal
  template:
    metadata:
      labels:
        app: harbor-portal
    spec:
      securityContext:apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
  namespace: harborfinal
  labels:
    app: harbor-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-portal
  template:
    metadata:
      labels:
        app: harbor-portal
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 1000
            capabilities:
              add: ["NET_BIND_SERVICE"]
          volumeMounts:
            - name: nginx-temp
              mountPath: /etc/nginx/client_body_temp
            - name: nginx-temp
              mountPath: /etc/nginx/proxy_temp
      volumes:
        - name: nginx-temp
          emptyDir: {}
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            capabilities:
              add: ["NET_BIND_SERVICE"]
