apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
  namespace: harborfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-portal
  template:
    metadata:
      labels:
        app: harbor-portal
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-temp
              mountPath: /etc/nginx/client_body_temp
      volumes:
        - name: nginx-temp
          emptyDir: {}
