apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-portal
  namespace: harborfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-portal
  template:
    metadata:
      labels:
        app: harbor-portal
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: portal
          image: goharbor/harbor-portal:v2.12.2
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: client-temp
              mountPath: /etc/nginx/client_body_temp
            - name: proxy-temp
              mountPath: /etc/nginx/proxy_temp
            - name: fastcgi-temp
              mountPath: /etc/nginx/fastcgi_temp
            - name: scgi-temp
              mountPath: /etc/nginx/scgi_temp
            - name: uwsgi-temp
              mountPath: /etc/nginx/uwsgi_temp
      volumes:
        - name: client-temp
          emptyDir: {}
        - name: proxy-temp
          emptyDir: {}
        - name: fastcgi-temp
          emptyDir: {}
        - name: scgi-temp
          emptyDir: {}
        - name: uwsgi-temp
          emptyDir: {}
