apiVersion: v1
kind: PersistentVolume
metadata:
  name: portal-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp3
  awsElasticBlockStore:
    volumeID: vol-09173d80e3b5e3db5
    fsType: ext4
