apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  volumeName: portal-pv
  resources:
    requests:
      storage: 5Gi
