apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-core
  namespace: harborfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: core
          image: goharbor/harbor-core:v2.12.2
          ports:
            - containerPort: 80
          env:
            - name: CACHE_REDIS_URL
              value: redis://harbor-redis:6379
          volumeMounts:
            - name: config
              mountPath: /etc/core/app.conf
              subPath: app.conf
      volumes:
        - name: config
          configMap:
            name: harbor-core-config
