apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-core-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-097daf816c0760af7   # 🔥 Replace with your actual EBS Volume ID
    fsType: ext4
