apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-core-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
