apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-core-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteMany  # Ensure this is supported by gp3-csi
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
