apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-core-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: harbor-core-pv
  resources:
    requests:
      storage: 5Gi
