apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-core-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-gp3
