apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-exporter
  namespace: harborfinal
  labels:
    app: postgresql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-exporter
  template:
    metadata:
      labels:
        app: postgresql-exporter
    spec:
      containers:
        - name: exporter
          image: postgresql-exporter:latest
          ports:
            - containerPort: 9187