apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
  namespace: harborfinal
  labels:
    app: harbor-jobservice
data:
  jobservice.conf: |
    log_level = info
    worker_pool_size = 10