apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
  namespace: harborfinal
data:
  config.yaml: |
    jobservice:
      redis_url: redis://harbor-redis:6379
    database:
      type: "postgresql"
      host: harbor-postgresql
      port: 5432
      username: postgres
      password: rootpassword  # Replace with your actual password
      database: registry
      sslmode: disable
