apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-jobservice
  namespace: harborfinal
  labels:
    app: harbor-jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-jobservice
  template:
    metadata:
      labels:
        app: harbor-jobservice
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: jobservice
          image: goharbor/harbor-jobservice:v2.12.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/jobservice/config.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /api/v1/stats
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/v1/stats
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
      volumes:
        - name: config-volume
          configMap:
            name: harbor-jobservice-config
