apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobservice-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp3
  awsElasticBlockStore:
    volumeID: vol-097daf816c0760af7
    fsType: ext4
