apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jobservice-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: jobservice-pv
  resources:
    requests:
      storage: 5Gi
      storageClassName: ebs-gp3

