apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-exporter
  namespace: harborfinal
  labels:
    app: harbor-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-exporter
  template:
    metadata:
      labels:
        app: harbor-exporter
    spec:
      containers:
        - name: exporter
          image: goharbor/harbor-exporter:v2.13.0-rc1
          ports:
            - containerPort: 8080
