apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor-exporter-monitor
  namespace: harborfinal
spec:
  selector:
    matchLabels:
      app: harbor-exporter
  endpoints:
    - port: 8080