apiVersion: v1
kind: Service
metadata:
  name: harbor-exporter
  namespace: harborfinal
  labels:
    app: harbor-exporter
spec:
  selector:
    app: harbor-exporter
  ports:
    - name: metrics
      port: 8080        # Port exposed by your exporter
      targetPort: 8080  # Container port
  type: LoadBalancer       # Use LoadBalancer if needed externally
