apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: harbor
  labels:
    app: harbor-registry
data:
  config.yml: |
    version: 0.1
    log:
      level: info
    storage:
      filesystem:
        rootdirectory: /storage
    http:
      addr: :5000
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3