apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-registry
  namespace: harborfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-registry
  template:
    metadata:
      labels:
        app: harbor-registry
    spec:
      containers:
      - name: registry
        image: <your-registry-image>
        volumeMounts:
        - name: config-volume
          mountPath: /etc/registry/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: registry-config
