apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: harborfinal
spec:
  capacity:
    storage: 50Gi
    volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
