apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: harbor
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi