apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  awsElasticBlockStore:
    volumeID: <EBS_VOLUME_ID_REGISTRY>
    fsType: ext4
