apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-gp3
  volumeName: registry-pv
  resources:
    requests:
      storage: 20Gi
