apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: harborfinal
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: registry-pv
  resources:
    requests:
      storage: 20Gi
