apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: harborfinal
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: exporter
          image: redis-exporter:latest
          ports:
            - containerPort: 9121