apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
  namespace: harborfinal
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: 9121