apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: harborfinal
spec:
  selector:
    app: redis-exporter
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
  type: LoadBalancer